/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.alterian.ja.model.ResourceType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ClearPermissionsRequest
 */
public class ClearPermissionsRequestTest {
    private final ClearPermissionsRequest model = new ClearPermissionsRequest();

    /**
     * Model tests for ClearPermissionsRequest
     */
    @Test
    public void testClearPermissionsRequest() {
        // TODO: test ClearPermissionsRequest
    }

    /**
     * Test the property 'isGroup'
     */
    @Test
    public void isGroupTest() {
        // TODO: test isGroup
    }

    /**
     * Test the property 'itemID'
     */
    @Test
    public void itemIDTest() {
        // TODO: test itemID
    }

    /**
     * Test the property 'itemType'
     */
    @Test
    public void itemTypeTest() {
        // TODO: test itemType
    }

    /**
     * Test the property 'securityID'
     */
    @Test
    public void securityIDTest() {
        // TODO: test securityID
    }

}
