/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CMTokenInformation
 */
public class CMTokenInformationTest {
    private final CMTokenInformation model = new CMTokenInformation();

    /**
     * Model tests for CMTokenInformation
     */
    @Test
    public void testCMTokenInformation() {
        // TODO: test CMTokenInformation
    }

    /**
     * Test the property 'ID'
     */
    @Test
    public void IDTest() {
        // TODO: test ID
    }

    /**
     * Test the property 'loginID'
     */
    @Test
    public void loginIDTest() {
        // TODO: test loginID
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'timezoneID'
     */
    @Test
    public void timezoneIDTest() {
        // TODO: test timezoneID
    }

    /**
     * Test the property 'userID'
     */
    @Test
    public void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'clientID'
     */
    @Test
    public void clientIDTest() {
        // TODO: test clientID
    }

    /**
     * Test the property 'lastActivity'
     */
    @Test
    public void lastActivityTest() {
        // TODO: test lastActivity
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'culture'
     */
    @Test
    public void cultureTest() {
        // TODO: test culture
    }

    /**
     * Test the property 'isStatic'
     */
    @Test
    public void isStaticTest() {
        // TODO: test isStatic
    }

    /**
     * Test the property 'isSAtoken'
     */
    @Test
    public void isSAtokenTest() {
        // TODO: test isSAtoken
    }

}
