/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateSankeyFavouriteRequest
 */
public class CreateSankeyFavouriteRequestTest {
    private final CreateSankeyFavouriteRequest model = new CreateSankeyFavouriteRequest();

    /**
     * Model tests for CreateSankeyFavouriteRequest
     */
    @Test
    public void testCreateSankeyFavouriteRequest() {
        // TODO: test CreateSankeyFavouriteRequest
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'eventTypes'
     */
    @Test
    public void eventTypesTest() {
        // TODO: test eventTypes
    }

    /**
     * Test the property 'initiatives'
     */
    @Test
    public void initiativesTest() {
        // TODO: test initiatives
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'periodInDays'
     */
    @Test
    public void periodInDaysTest() {
        // TODO: test periodInDays
    }

    /**
     * Test the property 'queueId'
     */
    @Test
    public void queueIdTest() {
        // TODO: test queueId
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
