/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateChannelRequest
 */
public class CreateChannelRequestTest {
    private final CreateChannelRequest model = new CreateChannelRequest();

    /**
     * Model tests for CreateChannelRequest
     */
    @Test
    public void testCreateChannelRequest() {
        // TODO: test CreateChannelRequest
    }

    /**
     * Test the property 'hexColour'
     */
    @Test
    public void hexColourTest() {
        // TODO: test hexColour
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
