/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EMDeleteListRequest
 */
public class EMDeleteListRequestTest {
    private final EMDeleteListRequest model = new EMDeleteListRequest();

    /**
     * Model tests for EMDeleteListRequest
     */
    @Test
    public void testEMDeleteListRequest() {
        // TODO: test EMDeleteListRequest
    }

    /**
     * Test the property 'emMappingId'
     */
    @Test
    public void emMappingIdTest() {
        // TODO: test emMappingId
    }

    /**
     * Test the property 'listId'
     */
    @Test
    public void listIdTest() {
        // TODO: test listId
    }

}
