/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EventStreamModel
 */
public class EventStreamModelTest {
    private final EventStreamModel model = new EventStreamModel();

    /**
     * Model tests for EventStreamModel
     */
    @Test
    public void testEventStreamModel() {
        // TODO: test EventStreamModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'queueId'
     */
    @Test
    public void queueIdTest() {
        // TODO: test queueId
    }

    /**
     * Test the property 'datasourceId'
     */
    @Test
    public void datasourceIdTest() {
        // TODO: test datasourceId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'started'
     */
    @Test
    public void startedTest() {
        // TODO: test started
    }

    /**
     * Test the property 'completed'
     */
    @Test
    public void completedTest() {
        // TODO: test completed
    }

    /**
     * Test the property 'trainingOptions'
     */
    @Test
    public void trainingOptionsTest() {
        // TODO: test trainingOptions
    }

    /**
     * Test the property 'engineModelName'
     */
    @Test
    public void engineModelNameTest() {
        // TODO: test engineModelName
    }

    /**
     * Test the property 'engineModelConfig'
     */
    @Test
    public void engineModelConfigTest() {
        // TODO: test engineModelConfig
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'testAccuracy'
     */
    @Test
    public void testAccuracyTest() {
        // TODO: test testAccuracy
    }

    /**
     * Test the property 'testlLoss'
     */
    @Test
    public void testlLossTest() {
        // TODO: test testlLoss
    }

}
