/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.alterian.ja.model.APICursor;
import com.alterian.ja.model.FolderTypes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetFoldersRequest
 */
public class GetFoldersRequestTest {
    private final GetFoldersRequest model = new GetFoldersRequest();

    /**
     * Model tests for GetFoldersRequest
     */
    @Test
    public void testGetFoldersRequest() {
        // TODO: test GetFoldersRequest
    }

    /**
     * Test the property 'cursor'
     */
    @Test
    public void cursorTest() {
        // TODO: test cursor
    }

    /**
     * Test the property 'folderType'
     */
    @Test
    public void folderTypeTest() {
        // TODO: test folderType
    }

    /**
     * Test the property 'getChildFolders'
     */
    @Test
    public void getChildFoldersTest() {
        // TODO: test getChildFolders
    }

    /**
     * Test the property 'includeChildCount'
     */
    @Test
    public void includeChildCountTest() {
        // TODO: test includeChildCount
    }

    /**
     * Test the property 'includeHidden'
     */
    @Test
    public void includeHiddenTest() {
        // TODO: test includeHidden
    }

    /**
     * Test the property 'parentFolder'
     */
    @Test
    public void parentFolderTest() {
        // TODO: test parentFolder
    }

}
