/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.alterian.ja.model.APICursor;
import com.alterian.ja.model.OpportunityMatrix;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetOpportunityMatrixDefaultResponse
 */
public class GetOpportunityMatrixDefaultResponseTest {
    private final GetOpportunityMatrixDefaultResponse model = new GetOpportunityMatrixDefaultResponse();

    /**
     * Model tests for GetOpportunityMatrixDefaultResponse
     */
    @Test
    public void testGetOpportunityMatrixDefaultResponse() {
        // TODO: test GetOpportunityMatrixDefaultResponse
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'debugMessage'
     */
    @Test
    public void debugMessageTest() {
        // TODO: test debugMessage
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'cursor'
     */
    @Test
    public void cursorTest() {
        // TODO: test cursor
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

}
