/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.alterian.ja.model.APICursor;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetTokensRequest
 */
public class GetTokensRequestTest {
    private final GetTokensRequest model = new GetTokensRequest();

    /**
     * Model tests for GetTokensRequest
     */
    @Test
    public void testGetTokensRequest() {
        // TODO: test GetTokensRequest
    }

    /**
     * Test the property 'clientID'
     */
    @Test
    public void clientIDTest() {
        // TODO: test clientID
    }

    /**
     * Test the property 'cursor'
     */
    @Test
    public void cursorTest() {
        // TODO: test cursor
    }

    /**
     * Test the property 'includeNonUser'
     */
    @Test
    public void includeNonUserTest() {
        // TODO: test includeNonUser
    }

    /**
     * Test the property 'includeSA'
     */
    @Test
    public void includeSATest() {
        // TODO: test includeSA
    }

    /**
     * Test the property 'includeStandard'
     */
    @Test
    public void includeStandardTest() {
        // TODO: test includeStandard
    }

    /**
     * Test the property 'includeStatic'
     */
    @Test
    public void includeStaticTest() {
        // TODO: test includeStatic
    }

}
