/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.alterian.ja.model.ColumnPublishedTransformSummary;
import com.alterian.ja.model.EventStreamTransition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryEventStreamResult
 */
public class QueryEventStreamResultTest {
    private final QueryEventStreamResult model = new QueryEventStreamResult();

    /**
     * Model tests for QueryEventStreamResult
     */
    @Test
    public void testQueryEventStreamResult() {
        // TODO: test QueryEventStreamResult
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

    /**
     * Test the property 'secondaryEvents'
     */
    @Test
    public void secondaryEventsTest() {
        // TODO: test secondaryEvents
    }

    /**
     * Test the property 'transitions'
     */
    @Test
    public void transitionsTest() {
        // TODO: test transitions
    }

    /**
     * Test the property 'transforms'
     */
    @Test
    public void transformsTest() {
        // TODO: test transforms
    }

}
