/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SaveDecodeListRequest
 */
public class SaveDecodeListRequestTest {
    private final SaveDecodeListRequest model = new SaveDecodeListRequest();

    /**
     * Model tests for SaveDecodeListRequest
     */
    @Test
    public void testSaveDecodeListRequest() {
        // TODO: test SaveDecodeListRequest
    }

    /**
     * Test the property 'copyVersion'
     */
    @Test
    public void copyVersionTest() {
        // TODO: test copyVersion
    }

    /**
     * Test the property 'createCopy'
     */
    @Test
    public void createCopyTest() {
        // TODO: test createCopy
    }

    /**
     * Test the property 'defaultLabel'
     */
    @Test
    public void defaultLabelTest() {
        // TODO: test defaultLabel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'replaceExisting'
     */
    @Test
    public void replaceExistingTest() {
        // TODO: test replaceExisting
    }

    /**
     * Test the property 'sourceLabels'
     */
    @Test
    public void sourceLabelsTest() {
        // TODO: test sourceLabels
    }

    /**
     * Test the property 'targetLabels'
     */
    @Test
    public void targetLabelsTest() {
        // TODO: test targetLabels
    }

}
