/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateRepeatingPatternItemScoresRequest
 */
public class UpdateRepeatingPatternItemScoresRequestTest {
    private final UpdateRepeatingPatternItemScoresRequest model = new UpdateRepeatingPatternItemScoresRequest();

    /**
     * Model tests for UpdateRepeatingPatternItemScoresRequest
     */
    @Test
    public void testUpdateRepeatingPatternItemScoresRequest() {
        // TODO: test UpdateRepeatingPatternItemScoresRequest
    }

    /**
     * Test the property 'decodeId'
     */
    @Test
    public void decodeIdTest() {
        // TODO: test decodeId
    }

    /**
     * Test the property 'decodeVersion'
     */
    @Test
    public void decodeVersionTest() {
        // TODO: test decodeVersion
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'patternId'
     */
    @Test
    public void patternIdTest() {
        // TODO: test patternId
    }

    /**
     * Test the property 'replaceExistingScores'
     */
    @Test
    public void replaceExistingScoresTest() {
        // TODO: test replaceExistingScores
    }

    /**
     * Test the property 'scores'
     */
    @Test
    public void scoresTest() {
        // TODO: test scores
    }

}
