/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.ja.JSON;

/**
 * AreDatasourceCampaignsPausedRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class AreDatasourceCampaignsPausedRequest {
  public static final String SERIALIZED_NAME_DATASOURCE_ID = "DatasourceId";
  @SerializedName(SERIALIZED_NAME_DATASOURCE_ID)
  private Integer datasourceId;

  public static final String SERIALIZED_NAME_LOG_WATCH_TIME = "LogWatchTime";
  @SerializedName(SERIALIZED_NAME_LOG_WATCH_TIME)
  private Integer logWatchTime;

  public AreDatasourceCampaignsPausedRequest() {
  }

  public AreDatasourceCampaignsPausedRequest datasourceId(Integer datasourceId) {
    this.datasourceId = datasourceId;
    return this;
  }

   /**
   * The id of the datasource that you want to check for activity
   * @return datasourceId
  **/
  @javax.annotation.Nullable
  public Integer getDatasourceId() {
    return datasourceId;
  }

  public void setDatasourceId(Integer datasourceId) {
    this.datasourceId = datasourceId;
  }


  public AreDatasourceCampaignsPausedRequest logWatchTime(Integer logWatchTime) {
    this.logWatchTime = logWatchTime;
    return this;
  }

   /**
   * How long (in seconds) should we watch for activity. Pass 0 if you do not want to watch for activity
   * @return logWatchTime
  **/
  @javax.annotation.Nullable
  public Integer getLogWatchTime() {
    return logWatchTime;
  }

  public void setLogWatchTime(Integer logWatchTime) {
    this.logWatchTime = logWatchTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AreDatasourceCampaignsPausedRequest areDatasourceCampaignsPausedRequest = (AreDatasourceCampaignsPausedRequest) o;
    return Objects.equals(this.datasourceId, areDatasourceCampaignsPausedRequest.datasourceId) &&
        Objects.equals(this.logWatchTime, areDatasourceCampaignsPausedRequest.logWatchTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasourceId, logWatchTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AreDatasourceCampaignsPausedRequest {\n");
    sb.append("    datasourceId: ").append(toIndentedString(datasourceId)).append("\n");
    sb.append("    logWatchTime: ").append(toIndentedString(logWatchTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DatasourceId");
    openapiFields.add("LogWatchTime");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AreDatasourceCampaignsPausedRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AreDatasourceCampaignsPausedRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AreDatasourceCampaignsPausedRequest is not found in the empty JSON string", AreDatasourceCampaignsPausedRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AreDatasourceCampaignsPausedRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AreDatasourceCampaignsPausedRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AreDatasourceCampaignsPausedRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AreDatasourceCampaignsPausedRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AreDatasourceCampaignsPausedRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AreDatasourceCampaignsPausedRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AreDatasourceCampaignsPausedRequest>() {
           @Override
           public void write(JsonWriter out, AreDatasourceCampaignsPausedRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AreDatasourceCampaignsPausedRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AreDatasourceCampaignsPausedRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AreDatasourceCampaignsPausedRequest
  * @throws IOException if the JSON string is invalid with respect to AreDatasourceCampaignsPausedRequest
  */
  public static AreDatasourceCampaignsPausedRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AreDatasourceCampaignsPausedRequest.class);
  }

 /**
  * Convert an instance of AreDatasourceCampaignsPausedRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

