/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import java.util.Objects;
import com.alterian.ja.model.DMConditionalValue;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.ja.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class DMVariableValue {
  public static final String SERIALIZED_NAME_CONDITIONAL_VALUES = "ConditionalValues";
  @SerializedName(SERIALIZED_NAME_CONDITIONAL_VALUES)
  private List<DMConditionalValue> conditionalValues;

  public static final String SERIALIZED_NAME_VALUE = "Value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public DMVariableValue() {
  }

  public DMVariableValue conditionalValues(List<DMConditionalValue> conditionalValues) {
    this.conditionalValues = conditionalValues;
    return this;
  }

  public DMVariableValue addConditionalValuesItem(DMConditionalValue conditionalValuesItem) {
    if (this.conditionalValues == null) {
      this.conditionalValues = new ArrayList<>();
    }
    this.conditionalValues.add(conditionalValuesItem);
    return this;
  }

   /**
   * 
   * @return conditionalValues
  **/
  @javax.annotation.Nullable
  public List<DMConditionalValue> getConditionalValues() {
    return conditionalValues;
  }

  public void setConditionalValues(List<DMConditionalValue> conditionalValues) {
    this.conditionalValues = conditionalValues;
  }


  public DMVariableValue value(String value) {
    this.value = value;
    return this;
  }

   /**
   * 
   * @return value
  **/
  @javax.annotation.Nullable
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DMVariableValue dmVariableValue = (DMVariableValue) o;
    return Objects.equals(this.conditionalValues, dmVariableValue.conditionalValues) &&
        Objects.equals(this.value, dmVariableValue.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditionalValues, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DMVariableValue {\n");
    sb.append("    conditionalValues: ").append(toIndentedString(conditionalValues)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ConditionalValues");
    openapiFields.add("Value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DMVariableValue
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DMVariableValue.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DMVariableValue is not found in the empty JSON string", DMVariableValue.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DMVariableValue.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DMVariableValue` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("ConditionalValues") != null && !jsonObj.get("ConditionalValues").isJsonNull()) {
        JsonArray jsonArrayconditionalValues = jsonObj.getAsJsonArray("ConditionalValues");
        if (jsonArrayconditionalValues != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ConditionalValues").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ConditionalValues` to be an array in the JSON string but got `%s`", jsonObj.get("ConditionalValues").toString()));
          }

          // validate the optional field `ConditionalValues` (array)
          for (int i = 0; i < jsonArrayconditionalValues.size(); i++) {
            DMConditionalValue.validateJsonElement(jsonArrayconditionalValues.get(i));
          };
        }
      }
      if ((jsonObj.get("Value") != null && !jsonObj.get("Value").isJsonNull()) && !jsonObj.get("Value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DMVariableValue.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DMVariableValue' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DMVariableValue> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DMVariableValue.class));

       return (TypeAdapter<T>) new TypeAdapter<DMVariableValue>() {
           @Override
           public void write(JsonWriter out, DMVariableValue value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DMVariableValue read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DMVariableValue given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DMVariableValue
  * @throws IOException if the JSON string is invalid with respect to DMVariableValue
  */
  public static DMVariableValue fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DMVariableValue.class);
  }

 /**
  * Convert an instance of DMVariableValue to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

