/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.ja.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class EventStreamTransition {
  public static final String SERIALIZED_NAME_INTERACTION = "Interaction";
  @SerializedName(SERIALIZED_NAME_INTERACTION)
  private Integer interaction;

  public static final String SERIALIZED_NAME_FROM = "From";
  @SerializedName(SERIALIZED_NAME_FROM)
  private Integer from;

  public static final String SERIALIZED_NAME_TO = "To";
  @SerializedName(SERIALIZED_NAME_TO)
  private Integer to;

  public static final String SERIALIZED_NAME_SECONDARY_FROM = "SecondaryFrom";
  @SerializedName(SERIALIZED_NAME_SECONDARY_FROM)
  private Integer secondaryFrom;

  public static final String SERIALIZED_NAME_SECONDARY_TO = "SecondaryTo";
  @SerializedName(SERIALIZED_NAME_SECONDARY_TO)
  private Integer secondaryTo;

  public static final String SERIALIZED_NAME_COUNT = "Count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Long count;

  public static final String SERIALIZED_NAME_IS_PREDICTION = "IsPrediction";
  @SerializedName(SERIALIZED_NAME_IS_PREDICTION)
  private Boolean isPrediction;

  public EventStreamTransition() {
  }

  public EventStreamTransition interaction(Integer interaction) {
    this.interaction = interaction;
    return this;
  }

   /**
   * 
   * @return interaction
  **/
  @javax.annotation.Nullable
  public Integer getInteraction() {
    return interaction;
  }

  public void setInteraction(Integer interaction) {
    this.interaction = interaction;
  }


  public EventStreamTransition from(Integer from) {
    this.from = from;
    return this;
  }

   /**
   * 
   * @return from
  **/
  @javax.annotation.Nullable
  public Integer getFrom() {
    return from;
  }

  public void setFrom(Integer from) {
    this.from = from;
  }


  public EventStreamTransition to(Integer to) {
    this.to = to;
    return this;
  }

   /**
   * 
   * @return to
  **/
  @javax.annotation.Nullable
  public Integer getTo() {
    return to;
  }

  public void setTo(Integer to) {
    this.to = to;
  }


  public EventStreamTransition secondaryFrom(Integer secondaryFrom) {
    this.secondaryFrom = secondaryFrom;
    return this;
  }

   /**
   * 
   * @return secondaryFrom
  **/
  @javax.annotation.Nullable
  public Integer getSecondaryFrom() {
    return secondaryFrom;
  }

  public void setSecondaryFrom(Integer secondaryFrom) {
    this.secondaryFrom = secondaryFrom;
  }


  public EventStreamTransition secondaryTo(Integer secondaryTo) {
    this.secondaryTo = secondaryTo;
    return this;
  }

   /**
   * 
   * @return secondaryTo
  **/
  @javax.annotation.Nullable
  public Integer getSecondaryTo() {
    return secondaryTo;
  }

  public void setSecondaryTo(Integer secondaryTo) {
    this.secondaryTo = secondaryTo;
  }


  public EventStreamTransition count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * 
   * @return count
  **/
  @javax.annotation.Nullable
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }


  public EventStreamTransition isPrediction(Boolean isPrediction) {
    this.isPrediction = isPrediction;
    return this;
  }

   /**
   * 
   * @return isPrediction
  **/
  @javax.annotation.Nullable
  public Boolean getIsPrediction() {
    return isPrediction;
  }

  public void setIsPrediction(Boolean isPrediction) {
    this.isPrediction = isPrediction;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventStreamTransition eventStreamTransition = (EventStreamTransition) o;
    return Objects.equals(this.interaction, eventStreamTransition.interaction) &&
        Objects.equals(this.from, eventStreamTransition.from) &&
        Objects.equals(this.to, eventStreamTransition.to) &&
        Objects.equals(this.secondaryFrom, eventStreamTransition.secondaryFrom) &&
        Objects.equals(this.secondaryTo, eventStreamTransition.secondaryTo) &&
        Objects.equals(this.count, eventStreamTransition.count) &&
        Objects.equals(this.isPrediction, eventStreamTransition.isPrediction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interaction, from, to, secondaryFrom, secondaryTo, count, isPrediction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventStreamTransition {\n");
    sb.append("    interaction: ").append(toIndentedString(interaction)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    secondaryFrom: ").append(toIndentedString(secondaryFrom)).append("\n");
    sb.append("    secondaryTo: ").append(toIndentedString(secondaryTo)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    isPrediction: ").append(toIndentedString(isPrediction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Interaction");
    openapiFields.add("From");
    openapiFields.add("To");
    openapiFields.add("SecondaryFrom");
    openapiFields.add("SecondaryTo");
    openapiFields.add("Count");
    openapiFields.add("IsPrediction");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EventStreamTransition
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EventStreamTransition.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EventStreamTransition is not found in the empty JSON string", EventStreamTransition.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EventStreamTransition.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EventStreamTransition` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventStreamTransition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventStreamTransition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventStreamTransition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventStreamTransition.class));

       return (TypeAdapter<T>) new TypeAdapter<EventStreamTransition>() {
           @Override
           public void write(JsonWriter out, EventStreamTransition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EventStreamTransition read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EventStreamTransition given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EventStreamTransition
  * @throws IOException if the JSON string is invalid with respect to EventStreamTransition
  */
  public static EventStreamTransition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventStreamTransition.class);
  }

 /**
  * Convert an instance of EventStreamTransition to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

