/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import java.util.Objects;
import com.alterian.ja.model.FieldTransformationSampleType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.ja.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class FieldTransformationSampleSettings {
  public static final String SERIALIZED_NAME_SAMPLE_TYPE = "SampleType";
  @SerializedName(SERIALIZED_NAME_SAMPLE_TYPE)
  private FieldTransformationSampleType sampleType;

  public static final String SERIALIZED_NAME_SAMPLE_SIZE = "SampleSize";
  @SerializedName(SERIALIZED_NAME_SAMPLE_SIZE)
  private Integer sampleSize;

  public static final String SERIALIZED_NAME_RANDOM_SEED = "RandomSeed";
  @SerializedName(SERIALIZED_NAME_RANDOM_SEED)
  private Integer randomSeed;

  public FieldTransformationSampleSettings() {
  }

  public FieldTransformationSampleSettings sampleType(FieldTransformationSampleType sampleType) {
    this.sampleType = sampleType;
    return this;
  }

   /**
   * Get sampleType
   * @return sampleType
  **/
  @javax.annotation.Nullable
  public FieldTransformationSampleType getSampleType() {
    return sampleType;
  }

  public void setSampleType(FieldTransformationSampleType sampleType) {
    this.sampleType = sampleType;
  }


  public FieldTransformationSampleSettings sampleSize(Integer sampleSize) {
    this.sampleSize = sampleSize;
    return this;
  }

   /**
   * 
   * @return sampleSize
  **/
  @javax.annotation.Nullable
  public Integer getSampleSize() {
    return sampleSize;
  }

  public void setSampleSize(Integer sampleSize) {
    this.sampleSize = sampleSize;
  }


  public FieldTransformationSampleSettings randomSeed(Integer randomSeed) {
    this.randomSeed = randomSeed;
    return this;
  }

   /**
   * 
   * @return randomSeed
  **/
  @javax.annotation.Nullable
  public Integer getRandomSeed() {
    return randomSeed;
  }

  public void setRandomSeed(Integer randomSeed) {
    this.randomSeed = randomSeed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldTransformationSampleSettings fieldTransformationSampleSettings = (FieldTransformationSampleSettings) o;
    return Objects.equals(this.sampleType, fieldTransformationSampleSettings.sampleType) &&
        Objects.equals(this.sampleSize, fieldTransformationSampleSettings.sampleSize) &&
        Objects.equals(this.randomSeed, fieldTransformationSampleSettings.randomSeed);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(sampleType, sampleSize, randomSeed);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldTransformationSampleSettings {\n");
    sb.append("    sampleType: ").append(toIndentedString(sampleType)).append("\n");
    sb.append("    sampleSize: ").append(toIndentedString(sampleSize)).append("\n");
    sb.append("    randomSeed: ").append(toIndentedString(randomSeed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("SampleType");
    openapiFields.add("SampleSize");
    openapiFields.add("RandomSeed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to FieldTransformationSampleSettings
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FieldTransformationSampleSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FieldTransformationSampleSettings is not found in the empty JSON string", FieldTransformationSampleSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FieldTransformationSampleSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FieldTransformationSampleSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `SampleType`
      if (jsonObj.get("SampleType") != null && !jsonObj.get("SampleType").isJsonNull()) {
        FieldTransformationSampleType.validateJsonElement(jsonObj.get("SampleType"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FieldTransformationSampleSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FieldTransformationSampleSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FieldTransformationSampleSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FieldTransformationSampleSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<FieldTransformationSampleSettings>() {
           @Override
           public void write(JsonWriter out, FieldTransformationSampleSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FieldTransformationSampleSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FieldTransformationSampleSettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FieldTransformationSampleSettings
  * @throws IOException if the JSON string is invalid with respect to FieldTransformationSampleSettings
  */
  public static FieldTransformationSampleSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FieldTransformationSampleSettings.class);
  }

 /**
  * Convert an instance of FieldTransformationSampleSettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

