/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import java.util.Objects;
import com.alterian.ja.model.APICursor;
import com.alterian.ja.model.ColumnMatchList;
import com.alterian.ja.model.EventStreamColumnTransform;
import com.alterian.ja.model.EventStreamPattern;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.ja.JSON;

/**
 * GetEventStreamAggregatesRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class GetEventStreamAggregatesRequest {
  public static final String SERIALIZED_NAME_COLUMN_TRANSFORMS = "ColumnTransforms";
  @SerializedName(SERIALIZED_NAME_COLUMN_TRANSFORMS)
  private List<EventStreamColumnTransform> columnTransforms;

  public static final String SERIALIZED_NAME_CURSOR = "Cursor";
  @SerializedName(SERIALIZED_NAME_CURSOR)
  private APICursor cursor;

  public static final String SERIALIZED_NAME_DATA_SOURCE_ID = "DataSourceId";
  @SerializedName(SERIALIZED_NAME_DATA_SOURCE_ID)
  private Integer dataSourceId;

  public static final String SERIALIZED_NAME_EVENT_DATE_TIME_LOWER = "EventDateTimeLower";
  @SerializedName(SERIALIZED_NAME_EVENT_DATE_TIME_LOWER)
  private OffsetDateTime eventDateTimeLower;

  public static final String SERIALIZED_NAME_EVENT_DATE_TIME_UPPER = "EventDateTimeUpper";
  @SerializedName(SERIALIZED_NAME_EVENT_DATE_TIME_UPPER)
  private OffsetDateTime eventDateTimeUpper;

  public static final String SERIALIZED_NAME_EVENT_STREAM_ID = "EventStreamId";
  @SerializedName(SERIALIZED_NAME_EVENT_STREAM_ID)
  private Integer eventStreamId;

  public static final String SERIALIZED_NAME_FILTERS = "Filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private List<ColumnMatchList> filters;

  public static final String SERIALIZED_NAME_IS_DATA_REFRESH_REQUIRED = "IsDataRefreshRequired";
  @SerializedName(SERIALIZED_NAME_IS_DATA_REFRESH_REQUIRED)
  private Boolean isDataRefreshRequired;

  public static final String SERIALIZED_NAME_PATTERN = "Pattern";
  @SerializedName(SERIALIZED_NAME_PATTERN)
  private EventStreamPattern pattern;

  public static final String SERIALIZED_NAME_TABLE_NAME_EX = "TableNameEx";
  @SerializedName(SERIALIZED_NAME_TABLE_NAME_EX)
  private String tableNameEx;

  public GetEventStreamAggregatesRequest() {
  }

  public GetEventStreamAggregatesRequest columnTransforms(List<EventStreamColumnTransform> columnTransforms) {
    this.columnTransforms = columnTransforms;
    return this;
  }

  public GetEventStreamAggregatesRequest addColumnTransformsItem(EventStreamColumnTransform columnTransformsItem) {
    if (this.columnTransforms == null) {
      this.columnTransforms = new ArrayList<>();
    }
    this.columnTransforms.add(columnTransformsItem);
    return this;
  }

   /**
   * Applies the specified transforms to base the result on the transformed discrete values
   * @return columnTransforms
  **/
  @javax.annotation.Nullable
  public List<EventStreamColumnTransform> getColumnTransforms() {
    return columnTransforms;
  }

  public void setColumnTransforms(List<EventStreamColumnTransform> columnTransforms) {
    this.columnTransforms = columnTransforms;
  }


  public GetEventStreamAggregatesRequest cursor(APICursor cursor) {
    this.cursor = cursor;
    return this;
  }

   /**
   * Get cursor
   * @return cursor
  **/
  @javax.annotation.Nullable
  public APICursor getCursor() {
    return cursor;
  }

  public void setCursor(APICursor cursor) {
    this.cursor = cursor;
  }


  public GetEventStreamAggregatesRequest dataSourceId(Integer dataSourceId) {
    this.dataSourceId = dataSourceId;
    return this;
  }

   /**
   * Datasource ID
   * @return dataSourceId
  **/
  @javax.annotation.Nullable
  public Integer getDataSourceId() {
    return dataSourceId;
  }

  public void setDataSourceId(Integer dataSourceId) {
    this.dataSourceId = dataSourceId;
  }


  public GetEventStreamAggregatesRequest eventDateTimeLower(OffsetDateTime eventDateTimeLower) {
    this.eventDateTimeLower = eventDateTimeLower;
    return this;
  }

   /**
   * Optionally filter by EventDateTime
   * @return eventDateTimeLower
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getEventDateTimeLower() {
    return eventDateTimeLower;
  }

  public void setEventDateTimeLower(OffsetDateTime eventDateTimeLower) {
    this.eventDateTimeLower = eventDateTimeLower;
  }


  public GetEventStreamAggregatesRequest eventDateTimeUpper(OffsetDateTime eventDateTimeUpper) {
    this.eventDateTimeUpper = eventDateTimeUpper;
    return this;
  }

   /**
   * Optionally filter by EventDateTime
   * @return eventDateTimeUpper
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getEventDateTimeUpper() {
    return eventDateTimeUpper;
  }

  public void setEventDateTimeUpper(OffsetDateTime eventDateTimeUpper) {
    this.eventDateTimeUpper = eventDateTimeUpper;
  }


  public GetEventStreamAggregatesRequest eventStreamId(Integer eventStreamId) {
    this.eventStreamId = eventStreamId;
    return this;
  }

   /**
   * Optionally invoke using an Event Stream ID instead of DataSourceId/TableNameEx. In this mode ColumnTransforms will be defaulted to those published against the columns of the Event Stream but can still be overridden if required
   * @return eventStreamId
  **/
  @javax.annotation.Nullable
  public Integer getEventStreamId() {
    return eventStreamId;
  }

  public void setEventStreamId(Integer eventStreamId) {
    this.eventStreamId = eventStreamId;
  }


  public GetEventStreamAggregatesRequest filters(List<ColumnMatchList> filters) {
    this.filters = filters;
    return this;
  }

  public GetEventStreamAggregatesRequest addFiltersItem(ColumnMatchList filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * Additional columns to filter on
   * @return filters
  **/
  @javax.annotation.Nullable
  public List<ColumnMatchList> getFilters() {
    return filters;
  }

  public void setFilters(List<ColumnMatchList> filters) {
    this.filters = filters;
  }


  public GetEventStreamAggregatesRequest isDataRefreshRequired(Boolean isDataRefreshRequired) {
    this.isDataRefreshRequired = isDataRefreshRequired;
    return this;
  }

   /**
   * Indicate whether the request can be satisfied with an existing cached result or requires recreation with latest data (default false). Has no effect if PatternId is specified
   * @return isDataRefreshRequired
  **/
  @javax.annotation.Nullable
  public Boolean getIsDataRefreshRequired() {
    return isDataRefreshRequired;
  }

  public void setIsDataRefreshRequired(Boolean isDataRefreshRequired) {
    this.isDataRefreshRequired = isDataRefreshRequired;
  }


  public GetEventStreamAggregatesRequest pattern(EventStreamPattern pattern) {
    this.pattern = pattern;
    return this;
  }

   /**
   * Get pattern
   * @return pattern
  **/
  @javax.annotation.Nullable
  public EventStreamPattern getPattern() {
    return pattern;
  }

  public void setPattern(EventStreamPattern pattern) {
    this.pattern = pattern;
  }


  public GetEventStreamAggregatesRequest tableNameEx(String tableNameEx) {
    this.tableNameEx = tableNameEx;
    return this;
  }

   /**
   * Event Stream table (standard two part name ex)
   * @return tableNameEx
  **/
  @javax.annotation.Nullable
  public String getTableNameEx() {
    return tableNameEx;
  }

  public void setTableNameEx(String tableNameEx) {
    this.tableNameEx = tableNameEx;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEventStreamAggregatesRequest getEventStreamAggregatesRequest = (GetEventStreamAggregatesRequest) o;
    return Objects.equals(this.columnTransforms, getEventStreamAggregatesRequest.columnTransforms) &&
        Objects.equals(this.cursor, getEventStreamAggregatesRequest.cursor) &&
        Objects.equals(this.dataSourceId, getEventStreamAggregatesRequest.dataSourceId) &&
        Objects.equals(this.eventDateTimeLower, getEventStreamAggregatesRequest.eventDateTimeLower) &&
        Objects.equals(this.eventDateTimeUpper, getEventStreamAggregatesRequest.eventDateTimeUpper) &&
        Objects.equals(this.eventStreamId, getEventStreamAggregatesRequest.eventStreamId) &&
        Objects.equals(this.filters, getEventStreamAggregatesRequest.filters) &&
        Objects.equals(this.isDataRefreshRequired, getEventStreamAggregatesRequest.isDataRefreshRequired) &&
        Objects.equals(this.pattern, getEventStreamAggregatesRequest.pattern) &&
        Objects.equals(this.tableNameEx, getEventStreamAggregatesRequest.tableNameEx);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnTransforms, cursor, dataSourceId, eventDateTimeLower, eventDateTimeUpper, eventStreamId, filters, isDataRefreshRequired, pattern, tableNameEx);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEventStreamAggregatesRequest {\n");
    sb.append("    columnTransforms: ").append(toIndentedString(columnTransforms)).append("\n");
    sb.append("    cursor: ").append(toIndentedString(cursor)).append("\n");
    sb.append("    dataSourceId: ").append(toIndentedString(dataSourceId)).append("\n");
    sb.append("    eventDateTimeLower: ").append(toIndentedString(eventDateTimeLower)).append("\n");
    sb.append("    eventDateTimeUpper: ").append(toIndentedString(eventDateTimeUpper)).append("\n");
    sb.append("    eventStreamId: ").append(toIndentedString(eventStreamId)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    isDataRefreshRequired: ").append(toIndentedString(isDataRefreshRequired)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    tableNameEx: ").append(toIndentedString(tableNameEx)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ColumnTransforms");
    openapiFields.add("Cursor");
    openapiFields.add("DataSourceId");
    openapiFields.add("EventDateTimeLower");
    openapiFields.add("EventDateTimeUpper");
    openapiFields.add("EventStreamId");
    openapiFields.add("Filters");
    openapiFields.add("IsDataRefreshRequired");
    openapiFields.add("Pattern");
    openapiFields.add("TableNameEx");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GetEventStreamAggregatesRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetEventStreamAggregatesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetEventStreamAggregatesRequest is not found in the empty JSON string", GetEventStreamAggregatesRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetEventStreamAggregatesRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetEventStreamAggregatesRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("ColumnTransforms") != null && !jsonObj.get("ColumnTransforms").isJsonNull()) {
        JsonArray jsonArraycolumnTransforms = jsonObj.getAsJsonArray("ColumnTransforms");
        if (jsonArraycolumnTransforms != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ColumnTransforms").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ColumnTransforms` to be an array in the JSON string but got `%s`", jsonObj.get("ColumnTransforms").toString()));
          }

          // validate the optional field `ColumnTransforms` (array)
          for (int i = 0; i < jsonArraycolumnTransforms.size(); i++) {
            EventStreamColumnTransform.validateJsonElement(jsonArraycolumnTransforms.get(i));
          };
        }
      }
      // validate the optional field `Cursor`
      if (jsonObj.get("Cursor") != null && !jsonObj.get("Cursor").isJsonNull()) {
        APICursor.validateJsonElement(jsonObj.get("Cursor"));
      }
      if (jsonObj.get("Filters") != null && !jsonObj.get("Filters").isJsonNull()) {
        JsonArray jsonArrayfilters = jsonObj.getAsJsonArray("Filters");
        if (jsonArrayfilters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("Filters").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `Filters` to be an array in the JSON string but got `%s`", jsonObj.get("Filters").toString()));
          }

          // validate the optional field `Filters` (array)
          for (int i = 0; i < jsonArrayfilters.size(); i++) {
            ColumnMatchList.validateJsonElement(jsonArrayfilters.get(i));
          };
        }
      }
      // validate the optional field `Pattern`
      if (jsonObj.get("Pattern") != null && !jsonObj.get("Pattern").isJsonNull()) {
        EventStreamPattern.validateJsonElement(jsonObj.get("Pattern"));
      }
      if ((jsonObj.get("TableNameEx") != null && !jsonObj.get("TableNameEx").isJsonNull()) && !jsonObj.get("TableNameEx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TableNameEx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TableNameEx").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetEventStreamAggregatesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetEventStreamAggregatesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetEventStreamAggregatesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetEventStreamAggregatesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GetEventStreamAggregatesRequest>() {
           @Override
           public void write(JsonWriter out, GetEventStreamAggregatesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetEventStreamAggregatesRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetEventStreamAggregatesRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetEventStreamAggregatesRequest
  * @throws IOException if the JSON string is invalid with respect to GetEventStreamAggregatesRequest
  */
  public static GetEventStreamAggregatesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetEventStreamAggregatesRequest.class);
  }

 /**
  * Convert an instance of GetEventStreamAggregatesRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

