/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.ja.JSON;

/**
 * GetGroupRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class GetGroupRequest {
  public static final String SERIALIZED_NAME_GROUP_I_D = "GroupID";
  @SerializedName(SERIALIZED_NAME_GROUP_I_D)
  private Integer groupID;

  public static final String SERIALIZED_NAME_INCLUDE_CONTAINED_GROUPS = "IncludeContainedGroups";
  @SerializedName(SERIALIZED_NAME_INCLUDE_CONTAINED_GROUPS)
  private Boolean includeContainedGroups;

  public static final String SERIALIZED_NAME_INCLUDE_MEMBERSHIP = "IncludeMembership";
  @SerializedName(SERIALIZED_NAME_INCLUDE_MEMBERSHIP)
  private Boolean includeMembership;

  public static final String SERIALIZED_NAME_INCLUDE_USERS = "IncludeUsers";
  @SerializedName(SERIALIZED_NAME_INCLUDE_USERS)
  private Boolean includeUsers;

  public GetGroupRequest() {
  }

  public GetGroupRequest groupID(Integer groupID) {
    this.groupID = groupID;
    return this;
  }

   /**
   * ID of the group to get
   * @return groupID
  **/
  @javax.annotation.Nullable
  public Integer getGroupID() {
    return groupID;
  }

  public void setGroupID(Integer groupID) {
    this.groupID = groupID;
  }


  public GetGroupRequest includeContainedGroups(Boolean includeContainedGroups) {
    this.includeContainedGroups = includeContainedGroups;
    return this;
  }

   /**
   * Include the groups that this group directly contains [fill in the Groups portion of the Members property]
   * @return includeContainedGroups
  **/
  @javax.annotation.Nullable
  public Boolean getIncludeContainedGroups() {
    return includeContainedGroups;
  }

  public void setIncludeContainedGroups(Boolean includeContainedGroups) {
    this.includeContainedGroups = includeContainedGroups;
  }


  public GetGroupRequest includeMembership(Boolean includeMembership) {
    this.includeMembership = includeMembership;
    return this;
  }

   /**
   * Include the groups to which this group is directly a member [fill in the Groups property]
   * @return includeMembership
  **/
  @javax.annotation.Nullable
  public Boolean getIncludeMembership() {
    return includeMembership;
  }

  public void setIncludeMembership(Boolean includeMembership) {
    this.includeMembership = includeMembership;
  }


  public GetGroupRequest includeUsers(Boolean includeUsers) {
    this.includeUsers = includeUsers;
    return this;
  }

   /**
   * Include the users that this group directly contains [fill in the Users portion of the Members property]
   * @return includeUsers
  **/
  @javax.annotation.Nullable
  public Boolean getIncludeUsers() {
    return includeUsers;
  }

  public void setIncludeUsers(Boolean includeUsers) {
    this.includeUsers = includeUsers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetGroupRequest getGroupRequest = (GetGroupRequest) o;
    return Objects.equals(this.groupID, getGroupRequest.groupID) &&
        Objects.equals(this.includeContainedGroups, getGroupRequest.includeContainedGroups) &&
        Objects.equals(this.includeMembership, getGroupRequest.includeMembership) &&
        Objects.equals(this.includeUsers, getGroupRequest.includeUsers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupID, includeContainedGroups, includeMembership, includeUsers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetGroupRequest {\n");
    sb.append("    groupID: ").append(toIndentedString(groupID)).append("\n");
    sb.append("    includeContainedGroups: ").append(toIndentedString(includeContainedGroups)).append("\n");
    sb.append("    includeMembership: ").append(toIndentedString(includeMembership)).append("\n");
    sb.append("    includeUsers: ").append(toIndentedString(includeUsers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("GroupID");
    openapiFields.add("IncludeContainedGroups");
    openapiFields.add("IncludeMembership");
    openapiFields.add("IncludeUsers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GetGroupRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetGroupRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetGroupRequest is not found in the empty JSON string", GetGroupRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetGroupRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetGroupRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetGroupRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetGroupRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetGroupRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetGroupRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GetGroupRequest>() {
           @Override
           public void write(JsonWriter out, GetGroupRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetGroupRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetGroupRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetGroupRequest
  * @throws IOException if the JSON string is invalid with respect to GetGroupRequest
  */
  public static GetGroupRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetGroupRequest.class);
  }

 /**
  * Convert an instance of GetGroupRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

