/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.ja.JSON;

/**
 * ListWebSpoonRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class ListWebSpoonRequest {
  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_INCLUDE_OPERATIONAL_STATUS = "IncludeOperationalStatus";
  @SerializedName(SERIALIZED_NAME_INCLUDE_OPERATIONAL_STATUS)
  private Boolean includeOperationalStatus;

  public ListWebSpoonRequest() {
  }

  public ListWebSpoonRequest id(String id) {
    this.id = id;
    return this;
  }

   /**
   * If you want a specific instance, provide the id here
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public ListWebSpoonRequest includeOperationalStatus(Boolean includeOperationalStatus) {
    this.includeOperationalStatus = includeOperationalStatus;
    return this;
  }

   /**
   * If you want to call out to the instance to see if it is reachable, specify yes.  For each instance, this will increase the time that this method takes to return
   * @return includeOperationalStatus
  **/
  @javax.annotation.Nullable
  public Boolean getIncludeOperationalStatus() {
    return includeOperationalStatus;
  }

  public void setIncludeOperationalStatus(Boolean includeOperationalStatus) {
    this.includeOperationalStatus = includeOperationalStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListWebSpoonRequest listWebSpoonRequest = (ListWebSpoonRequest) o;
    return Objects.equals(this.id, listWebSpoonRequest.id) &&
        Objects.equals(this.includeOperationalStatus, listWebSpoonRequest.includeOperationalStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, includeOperationalStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListWebSpoonRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    includeOperationalStatus: ").append(toIndentedString(includeOperationalStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Id");
    openapiFields.add("IncludeOperationalStatus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ListWebSpoonRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListWebSpoonRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListWebSpoonRequest is not found in the empty JSON string", ListWebSpoonRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListWebSpoonRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListWebSpoonRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("Id") != null && !jsonObj.get("Id").isJsonNull()) && !jsonObj.get("Id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListWebSpoonRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListWebSpoonRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListWebSpoonRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListWebSpoonRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ListWebSpoonRequest>() {
           @Override
           public void write(JsonWriter out, ListWebSpoonRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListWebSpoonRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ListWebSpoonRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ListWebSpoonRequest
  * @throws IOException if the JSON string is invalid with respect to ListWebSpoonRequest
  */
  public static ListWebSpoonRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListWebSpoonRequest.class);
  }

 /**
  * Convert an instance of ListWebSpoonRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

