/*
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.ja.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.ja.JSON;

/**
 * Definition of a Sankey
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class SankeyFavourite {
  public static final String SERIALIZED_NAME_I_D = "ID";
  @SerializedName(SERIALIZED_NAME_I_D)
  private Integer ID;

  public static final String SERIALIZED_NAME_QUEUE_ID = "QueueId";
  @SerializedName(SERIALIZED_NAME_QUEUE_ID)
  private Integer queueId;

  public static final String SERIALIZED_NAME_USER_ID = "UserId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_EVENT_TYPES = "EventTypes";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPES)
  private List<String> eventTypes;

  public static final String SERIALIZED_NAME_INITIATIVES = "Initiatives";
  @SerializedName(SERIALIZED_NAME_INITIATIVES)
  private List<String> initiatives;

  public static final String SERIALIZED_NAME_START_DT_TM = "StartDtTm";
  @SerializedName(SERIALIZED_NAME_START_DT_TM)
  private OffsetDateTime startDtTm;

  public static final String SERIALIZED_NAME_END_DT_TM = "EndDtTm";
  @SerializedName(SERIALIZED_NAME_END_DT_TM)
  private OffsetDateTime endDtTm;

  public static final String SERIALIZED_NAME_PERIOD_IN_DAYS = "PeriodInDays";
  @SerializedName(SERIALIZED_NAME_PERIOD_IN_DAYS)
  private Integer periodInDays;

  public SankeyFavourite() {
  }

  public SankeyFavourite ID(Integer ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Initiative ID
   * @return ID
  **/
  @javax.annotation.Nullable
  public Integer getID() {
    return ID;
  }

  public void setID(Integer ID) {
    this.ID = ID;
  }


  public SankeyFavourite queueId(Integer queueId) {
    this.queueId = queueId;
    return this;
  }

   /**
   * Queue ID
   * @return queueId
  **/
  @javax.annotation.Nullable
  public Integer getQueueId() {
    return queueId;
  }

  public void setQueueId(Integer queueId) {
    this.queueId = queueId;
  }


  public SankeyFavourite userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * User ID (Null for public)
   * @return userId
  **/
  @javax.annotation.Nullable
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  public SankeyFavourite name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the Sankey Favourite
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public SankeyFavourite eventTypes(List<String> eventTypes) {
    this.eventTypes = eventTypes;
    return this;
  }

  public SankeyFavourite addEventTypesItem(String eventTypesItem) {
    if (this.eventTypes == null) {
      this.eventTypes = new ArrayList<>();
    }
    this.eventTypes.add(eventTypesItem);
    return this;
  }

   /**
   * Event Types
   * @return eventTypes
  **/
  @javax.annotation.Nullable
  public List<String> getEventTypes() {
    return eventTypes;
  }

  public void setEventTypes(List<String> eventTypes) {
    this.eventTypes = eventTypes;
  }


  public SankeyFavourite initiatives(List<String> initiatives) {
    this.initiatives = initiatives;
    return this;
  }

  public SankeyFavourite addInitiativesItem(String initiativesItem) {
    if (this.initiatives == null) {
      this.initiatives = new ArrayList<>();
    }
    this.initiatives.add(initiativesItem);
    return this;
  }

   /**
   * Initiatives
   * @return initiatives
  **/
  @javax.annotation.Nullable
  public List<String> getInitiatives() {
    return initiatives;
  }

  public void setInitiatives(List<String> initiatives) {
    this.initiatives = initiatives;
  }


  public SankeyFavourite startDtTm(OffsetDateTime startDtTm) {
    this.startDtTm = startDtTm;
    return this;
  }

   /**
   * 
   * @return startDtTm
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getStartDtTm() {
    return startDtTm;
  }

  public void setStartDtTm(OffsetDateTime startDtTm) {
    this.startDtTm = startDtTm;
  }


  public SankeyFavourite endDtTm(OffsetDateTime endDtTm) {
    this.endDtTm = endDtTm;
    return this;
  }

   /**
   * 
   * @return endDtTm
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getEndDtTm() {
    return endDtTm;
  }

  public void setEndDtTm(OffsetDateTime endDtTm) {
    this.endDtTm = endDtTm;
  }


  public SankeyFavourite periodInDays(Integer periodInDays) {
    this.periodInDays = periodInDays;
    return this;
  }

   /**
   * 
   * @return periodInDays
  **/
  @javax.annotation.Nullable
  public Integer getPeriodInDays() {
    return periodInDays;
  }

  public void setPeriodInDays(Integer periodInDays) {
    this.periodInDays = periodInDays;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SankeyFavourite sankeyFavourite = (SankeyFavourite) o;
    return Objects.equals(this.ID, sankeyFavourite.ID) &&
        Objects.equals(this.queueId, sankeyFavourite.queueId) &&
        Objects.equals(this.userId, sankeyFavourite.userId) &&
        Objects.equals(this.name, sankeyFavourite.name) &&
        Objects.equals(this.eventTypes, sankeyFavourite.eventTypes) &&
        Objects.equals(this.initiatives, sankeyFavourite.initiatives) &&
        Objects.equals(this.startDtTm, sankeyFavourite.startDtTm) &&
        Objects.equals(this.endDtTm, sankeyFavourite.endDtTm) &&
        Objects.equals(this.periodInDays, sankeyFavourite.periodInDays);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, queueId, userId, name, eventTypes, initiatives, startDtTm, endDtTm, periodInDays);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SankeyFavourite {\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    queueId: ").append(toIndentedString(queueId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    eventTypes: ").append(toIndentedString(eventTypes)).append("\n");
    sb.append("    initiatives: ").append(toIndentedString(initiatives)).append("\n");
    sb.append("    startDtTm: ").append(toIndentedString(startDtTm)).append("\n");
    sb.append("    endDtTm: ").append(toIndentedString(endDtTm)).append("\n");
    sb.append("    periodInDays: ").append(toIndentedString(periodInDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ID");
    openapiFields.add("QueueId");
    openapiFields.add("UserId");
    openapiFields.add("Name");
    openapiFields.add("EventTypes");
    openapiFields.add("Initiatives");
    openapiFields.add("StartDtTm");
    openapiFields.add("EndDtTm");
    openapiFields.add("PeriodInDays");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SankeyFavourite
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SankeyFavourite.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SankeyFavourite is not found in the empty JSON string", SankeyFavourite.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SankeyFavourite.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SankeyFavourite` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) && !jsonObj.get("Name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("EventTypes") != null && !jsonObj.get("EventTypes").isJsonNull() && !jsonObj.get("EventTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `EventTypes` to be an array in the JSON string but got `%s`", jsonObj.get("EventTypes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("Initiatives") != null && !jsonObj.get("Initiatives").isJsonNull() && !jsonObj.get("Initiatives").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `Initiatives` to be an array in the JSON string but got `%s`", jsonObj.get("Initiatives").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SankeyFavourite.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SankeyFavourite' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SankeyFavourite> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SankeyFavourite.class));

       return (TypeAdapter<T>) new TypeAdapter<SankeyFavourite>() {
           @Override
           public void write(JsonWriter out, SankeyFavourite value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SankeyFavourite read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SankeyFavourite given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SankeyFavourite
  * @throws IOException if the JSON string is invalid with respect to SankeyFavourite
  */
  public static SankeyFavourite fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SankeyFavourite.class);
  }

 /**
  * Convert an instance of SankeyFavourite to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

